// <auto-generated />
using System;
using Divorcios.Datos.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Divorcios.Datos.Migraciones
{
    [DbContext(typeof(DivorciosDbContext))]
    [Migration("20260917220610_InicialIdentidadCaso")]
    partial class InicialIdentidadCaso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("divorcios")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Divorcios.Dominio.Entidades.Caso", b =>
                {
                    b.Property<long>("CasoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("caso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CasoId"));

                    b.Property<DateTime?>("CerradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrado_en");

                    b.Property<string>("CodigoPre")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("codigo_pre");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreadoPorCuentaId")
                        .HasColumnType("bigint")
                        .HasColumnName("creado_por_cuenta_id");

                    b.HasKey("CasoId")
                        .HasName("pk_caso");

                    b.HasIndex("CodigoPre")
                        .IsUnique()
                        .HasDatabaseName("ix_caso_codigo_pre");

                    b.HasIndex("CreadoPorCuentaId")
                        .HasDatabaseName("ix_caso_creado_por_cuenta_id");

                    b.ToTable("caso", "divorcios", t =>
                        {
                            t.HasCheckConstraint("ck_caso_fechas", "cerrado_en IS NULL OR cerrado_en >= creado_en");
                        });
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.CasoConyuge", b =>
                {
                    b.Property<long>("CasoConyugeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("caso_conyuge_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CasoConyugeId"));

                    b.Property<long>("CasoId")
                        .HasColumnType("bigint")
                        .HasColumnName("caso_id");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnName("persona_id");

                    b.Property<string>("PosicionCodigo")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("posicion_codigo");

                    b.HasKey("CasoConyugeId")
                        .HasName("pk_caso_conyuge");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("ix_caso_conyuge_persona_id");

                    b.HasIndex("CasoId", "PersonaId")
                        .IsUnique()
                        .HasDatabaseName("ix_caso_conyuge_caso_id_persona_id");

                    b.HasIndex("CasoId", "PosicionCodigo")
                        .IsUnique()
                        .HasDatabaseName("ix_caso_conyuge_caso_id_posicion_codigo");

                    b.ToTable("caso_conyuge", "divorcios", t =>
                        {
                            t.HasCheckConstraint("ck_conyuge_posicion", "posicion_codigo IN ('A', 'B')");
                        });
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.CuentaCiudadana", b =>
                {
                    b.Property<long>("CuentaCiudadanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cuenta_ciudadana_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CuentaCiudadanaId"));

                    b.Property<DateTime?>("BloqueadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_en");

                    b.Property<DateTime?>("CelularVerificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("celular_verificado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint")
                        .HasColumnName("persona_id");

                    b.HasKey("CuentaCiudadanaId")
                        .HasName("pk_cuenta_ciudadana");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("ix_cuenta_ciudadana_persona_id");

                    b.ToTable("cuenta_ciudadana", "divorcios");
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.Persona", b =>
                {
                    b.Property<long>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("persona_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("PersonaId"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("celular");

                    b.Property<string>("Correo")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DireccionDni")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion_dni");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombres");

                    b.Property<DateTime?>("VerificadoReniecEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificado_reniec_en");

                    b.HasKey("PersonaId")
                        .HasName("pk_persona");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("ix_persona_dni");

                    b.ToTable("persona", "divorcios", t =>
                        {
                            t.HasCheckConstraint("ck_persona_apellido_materno", "btrim(apellido_materno) <> ''");

                            t.HasCheckConstraint("ck_persona_apellido_paterno", "btrim(apellido_paterno) <> ''");

                            t.HasCheckConstraint("ck_persona_celular", "celular IS NULL OR celular ~ '^\\+?[0-9]{9,15}$'");

                            t.HasCheckConstraint("ck_persona_dni", "dni ~ '^[0-9]{8}$'");

                            t.HasCheckConstraint("ck_persona_nombres", "btrim(nombres) <> ''");
                        });
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.UsuarioInterno", b =>
                {
                    b.Property<long>("UsuarioInternoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_interno_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UsuarioInternoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("login");

                    b.Property<string>("NombreVisible")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nombre_visible");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RolCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol_codigo");

                    b.HasKey("UsuarioInternoId")
                        .HasName("pk_usuario_interno");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_interno_login");

                    b.ToTable("usuario_interno", "divorcios", t =>
                        {
                            t.HasCheckConstraint("ck_usuario_hash", "btrim(password_hash) <> ''");

                            t.HasCheckConstraint("ck_usuario_login", "btrim(login) <> ''");

                            t.HasCheckConstraint("ck_usuario_rol", "rol_codigo IN ('ADMIN', 'ABOGADA', 'ASISTENTE')");
                        });
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.ValidacionIdentidad", b =>
                {
                    b.Property<long>("ValidacionIdentidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("validacion_identidad_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ValidacionIdentidadId"));

                    b.Property<long>("CuentaCiudadanaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cuenta_ciudadana_id");

                    b.Property<string>("ProveedorCodigo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasDefaultValue("RENIEC")
                        .HasColumnName("proveedor_codigo");

                    b.Property<string>("ReferenciaConsulta")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("referencia_consulta");

                    b.Property<string>("ResultadoCodigo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("resultado_codigo");

                    b.Property<DateTime>("ValidadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validado_en")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ValidacionIdentidadId")
                        .HasName("pk_validacion_identidad");

                    b.HasIndex("CuentaCiudadanaId")
                        .HasDatabaseName("ix_validacion_identidad_cuenta_ciudadana_id");

                    b.ToTable("validacion_identidad", "divorcios", t =>
                        {
                            t.HasCheckConstraint("ck_validacion_resultado", "resultado_codigo IN ('VALIDO', 'NO_VALIDO', 'ERROR')");
                        });
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.Caso", b =>
                {
                    b.HasOne("Divorcios.Dominio.Entidades.CuentaCiudadana", "CreadoPorCuenta")
                        .WithMany("CasosCreados")
                        .HasForeignKey("CreadoPorCuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_caso_cuentas_ciudadanas_creado_por_cuenta_id");

                    b.Navigation("CreadoPorCuenta");
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.CasoConyuge", b =>
                {
                    b.HasOne("Divorcios.Dominio.Entidades.Caso", "Caso")
                        .WithMany("Conyuges")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caso_conyuge_caso_caso_id");

                    b.HasOne("Divorcios.Dominio.Entidades.Persona", "Persona")
                        .WithMany("CasosConyuge")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caso_conyuge_personas_persona_id");

                    b.Navigation("Caso");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.CuentaCiudadana", b =>
                {
                    b.HasOne("Divorcios.Dominio.Entidades.Persona", "Persona")
                        .WithOne("CuentaCiudadana")
                        .HasForeignKey("Divorcios.Dominio.Entidades.CuentaCiudadana", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuenta_ciudadana_personas_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.ValidacionIdentidad", b =>
                {
                    b.HasOne("Divorcios.Dominio.Entidades.CuentaCiudadana", "CuentaCiudadana")
                        .WithMany("ValidacionesIdentidad")
                        .HasForeignKey("CuentaCiudadanaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_validacion_identidad_cuenta_ciudadana_cuenta_ciudadana_id");

                    b.Navigation("CuentaCiudadana");
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.Caso", b =>
                {
                    b.Navigation("Conyuges");
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.CuentaCiudadana", b =>
                {
                    b.Navigation("CasosCreados");

                    b.Navigation("ValidacionesIdentidad");
                });

            modelBuilder.Entity("Divorcios.Dominio.Entidades.Persona", b =>
                {
                    b.Navigation("CasosConyuge");

                    b.Navigation("CuentaCiudadana");
                });
#pragma warning restore 612, 618
        }
    }
}
